# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s10:
      dhcp4: true
    enp0s3:
#      dhcp4: true
      addresses: [192.168.18.56/24]
      gateway4: 192.168.18.1
      nameservers:
       addresses: [8.8.8.8, 8.8.4.4]
    enp0s9:
      dhcp4: true
  version: 2
